server:
  port: 8888

spring:
  application:
    name: eurekaserver

eureka:
  instance:
    hostname: eureka01
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://eureka02:8889/eureka